### ISSUE TITLE
Showing Incorrect page size

### ISSUE THREAD

**Issue by sreevisakh** [sematext/sematable#70] opened 2017-12-13 08:17 UTC
If there are only 10 items in the table and if we select pageSize as 50 it is showing 50 of 10 which is incorrect

expected behaviour:
if the selected page size is less than filtered page size show the filteresd page size.
![screen shot 2017-12-13 at 1 46 54 pm](https://user-images.githubusercontent.com/866258/33928510-232a1a5e-e00c-11e7-94bb-57da267b32b6.png)

**Comment by otisg** [comment] 2017-12-13 22:38
I think this is a dupe of #35.

**Closed by otisg** 2017-12-13 22:38 UTC
